name: plotly
version: 0.8.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Interactive, browser-based charting library
homepage: https://github.com/rwl/plotly
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

# web:
#   compiler:
#     debug: dartdevc
dependencies:
  js: ^0.6.1+1
  
environment:
  sdk: '>=2.10.0 <3.0.0'